[project]
name = "rag-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.4",
    "pypdf>=6.16.0",
    "python-docx>=1.2.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
